version: '3.9'

services:
  nginx:
    container_name: nginx
    build: 
      context: ./nginx
      dockerfile: ./Dockerfile
    ports:
      - 80:80
      - 443:443
    restart: always
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    volumes:
      - /etc/letsencrypt/live/linuxstory.com/:/etc/letsencrypt/live/linuxstory.com/
      - /etc/letsencrypt/:/etc/letsencrypt
    depends_on:
      - nuxt
    networks:
      default:
        ipv4_address: 192.168.233.233

  nuxt:
    container_name: nuxt
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    expose:
      - 3000
    restart: always
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    networks:
      default:
        ipv4_address: 192.168.233.234

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.233.0/24
          gateway: 192.168.233.1